### PR TITLE
Feat: Add BSD 3-Clause License

### PR DESCRIPTION
**Pull request by adityaoberai**
## What does this PR do?

Add BSD 3-Clause License (from the main Appwrite repo)

## Test Plan

No plan necessary

## Related PRs and Issues

None

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Review by stnguyen90 — APPROVED** [review]
Confirmed this matches https://raw.githubusercontent.com/appwrite/appwrite/master/LICENSE

**Comment by eldadfux** [comment]
Will this make the default license BSD-3? How will it affect our MIT repos?

**Comment by eldadfux** [comment]
I wander if should be more pro-active about choosing the license rather than having a default.

**Comment by stnguyen90** [comment]
> Will this make the default license BSD-3? How will it affect our MIT repos?

Any repo without a license file will default to this one.

**Comment by stnguyen90** [comment]
> I wander if should be more pro-active about choosing the license rather than having a default.

Sure.

**Review by eldadfux — APPROVED** [review]

**Pull request merged**
